language: csharp

mono:
 - latest
 - 4.4.1

os:
 - linux

env:
 - TRAVIS_OS_UNAME=$(uname -s)

solution: StreamCryptor.sln

before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
  
install:
 - mono .nuget/nuget.exe restore StreamCryptor.sln -Verbosity detailed
 - mono .nuget/nuget.exe install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner

before_script:
 - bash travis-build-libsodium.sh

script:
 - xbuild StreamCryptor.sln
 - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Tests/bin/Debug/Tests.dll